trying to fix the exit code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,7 +6,7 @@ jobs:
       - BOOST_LIBRARY=process
       - CXX_STANDARD=gnu++11
     docker:
-      - image: gcc:6
+      - image: gcc:7
     steps:
       - checkout
       - run:
@@ -55,22 +55,22 @@ jobs:
           name: Building examples
           command: |
             cd $BOOST_REMOVE/example
-            ../../../b2 -j8 address-model=64 architecture=x86 toolset=gcc cxxflags="-std=gnu++14" -sBOOST_BUILD_PATH=. | tee example.log || RES=$?
-            sed -i -e "s/^..\/..\/..\/boost\/process\//$HOME_SED\/project\/include\/process\//gm" example.log
+            ../../../b2 -j8 address-model=64 architecture=x86 toolset=gcc cxxflags="-std=gnu++14" -sBOOST_BUILD_PATH=. | tee example.log || FAILED=1
+            sed -i -e "s/^..\/..\/..\/boost\/process\//\/root\/project\/include\/process\//gm" example.log
             python <(curl -s https://report.ci/annotate.py) --tool gcc --name "Circle CI Gcc Build" --input example.log
-            exit $RES
+            exit FAILED
       - run:
           name: Running Unit tests
           command: |
             cd $BOOST_REMOVE/test
-            ../../../b2 -j8 with-valgrind address-model=64 architecture=x86 testing.launcher=valgrind valgrind=on toolset=gcc cxxflags="--coverage -std=$CXX_STANDARD" linkflags="--coverage" -sBOOST_BUILD_PATH=. | tee test.log || RES=$?
-            ../../../b2 -j8 without-valgrind address-model=64 architecture=x86 toolset=gcc cxxflags="--coverage -std=$CXX_STANDARD" linkflags="--coverage" -sBOOST_BUILD_PATH=. | tee no-valgrind.log || RES=$?
-            sed -i -e "s/^..\/..\/..\/boost\/process\//$HOME_SED\/project\/include\/process\//gm" test.log
-            sed -i -e "s/^..\/..\/..\/boost\/process\//$HOME_SED\/project\/include\/process\//gm" no-valgrind.log
+            ../../../b2 -j8 with-valgrind address-model=64 architecture=x86 testing.launcher=valgrind valgrind=on toolset=gcc cxxflags="--coverage -std=$CXX_STANDARD" linkflags="--coverage" -sBOOST_BUILD_PATH=. | tee test.log || FAILED=1
+            ../../../b2 -j8 without-valgrind address-model=64 architecture=x86 toolset=gcc cxxflags="--coverage -std=$CXX_STANDARD" linkflags="--coverage" -sBOOST_BUILD_PATH=. | tee no-valgrind.log || FAILED=1
+            sed -i -e "s/^..\/..\/..\/boost\/process\//\/root\/project\/include\/process\//gm" test.log
+            sed -i -e "s/^..\/..\/..\/boost\/process\//\/root\/project\/include\/process\//gm" no-valgrind.log
 
             python <(curl -s https://report.ci/annotate.py) --tool gcc --input test.log
             python <(curl -s https://report.ci/annotate.py) --tool gcc --input no-valgrind.log
             python <(curl -s https://report.ci/upload.py) --name "Circle CI Gcc Tests" --framework boost
             bash <(curl -s https://codecov.io/bash) -x gcov || true
-            echo "BUILD_RESULT: $RES_1$RES_2"
-            exit $RES_1$RES_2
+            echo "BUILD_RESULT: $FAILED"
+            exit $FAILED
